### ISSUE TITLE
Logs fail with no RTC

### ISSUE THREAD

**Issue by thetazero** [PyCubed-Mini/flight_software#322]

**Comment by tomyyyD** [comment]
You might know this already, but from running in the emulator it appears that the logs fail because the filename is dependent on rtc.datetime and if there's no rtc then it can't get rtc.datetime, so is this bug more along the lines of finding a way to get the date and time for the log file without using rtc.datetime if there is no rtc?

**Comment by jbwillis** [comment]
Resolved by #336
