### ISSUE TITLE
Make magnetorquer coils accesible 

### ISSUE THREAD

**Issue by thetazero** [PyCubed-Mini/flight_software#63]
From my understanding there is no way to interact with the magnetorquer coils via the pycubed library right now.

**Comment by yashika-batra** [comment]
This is fixed in the new update. The coil library has a very basic function (vset) that sets the voltage in the coils. I've made a driver that lets us select a given coil and then set the voltage for that coil. This hasn't been hardware tested yet (because we don't have access to a fully assembled cubesat), but it's included in the current version of the library. You can look over it in the next review.

**Comment by thetazero** [comment]
That's awesome, I think we should close this issue after we've tested in on a flat sat

**Comment by thetazero** [comment]
Should be completed in #77
