### ISSUE TITLE
Figure out why voltage readings are averaged out over 50 itterations.

### ISSUE THREAD

**Issue by thetazero** [PyCubed-Mini/flight_software#87]
Current battery voltage source code:
```python3 
def battery_voltage():
    """ return the battery voltage """
    # initialize vbat
    vbat = 0

    for _ in range(50):
        # 65536 = 2^16, number of increments we can have to voltage
        vbat += _cubesat._vbatt.value * 3.3 / 65536
    # 100k/100k voltage divider
    voltage = (vbat / 50) * (100 + 100) / 100

    # volts
    return voltage

**Comment by yashika-batra** [comment]
This function loops 50 times for the reason we suspected - cubesat._vbatt is an instance of AnalogIn, which is an analog to digital converter. When we access the value of this object, we get the approximate voltage read from the board.BATTERY pin. Reading this 50 times, and then later averaging the value (vbat / 50) is likely just done so we can ensure we get a reliable reading (Likely because we're reading an analog value, so just one read can't be trusted)

**Comment by yashika-batra** [comment]
I've added comments that clarify what we're doing, and added the "why" to the docstring

**Comment by thetazero** [comment]
Thanks @yashika-batra
